name: Pipaline 

on:

  push:

    branches: [main]


        jobs: 
            build:
            runs-on: ubuntu-latest

            steps:  
             -users: actions/checkout@v3
             -name: Setup Node
            uses: actions/setup-node@v3
          
        width: 
            node-version: 18
        run: npm install    
        run: npm run test



